version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - dependencies
    open-pull-requests-limit: 1024 # A large value can be set to effectively remove the open pull request limit. # https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference#open-pull-requests-limit-
  - package-ecosystem: npm
    directories:
      - "/slides/*"
    schedule:
      interval: "daily"
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    labels:
      - dependencies
    versioning-strategy: increase
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      nix:
        patterns:
          - "*"
    labels:
      - "dependencies"
