version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: "/demystifying-the-nix-store"
    schedule:
      interval: "daily"
    groups:
      npm:
        patterns:
          - "*"
    labels:
      - dependencies
    : increase
  - package-ecosystem: npm
    directory: "/tracking-nixpkgs-pull-requests"
    schedule:
      interval: "daily"
    groups:
      npm:
        patterns:
          - "*"
    labels:
      - dependencies
    versioning-strategy: increase
