on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * 0" # At 00:00 on Sunday.
  workflow_dispatch:
permissions: {}
concurrency:
  group: "deploy-pages"
  cancel-in-progress: true
jobs:
  build-slides:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        slide:
          - name: running-kernel-based-virtual-machine
          - name: governing-azure-resources-with-policy
          - name: tracking-nixpkgs-merged-pull-requests
          - name: demystifying-the-nix-store
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "lts/*"
      - name: Install Dependencies
        working-directory: slides/${{ matrix.slide.name }}
        run: npm ci
      - name: Build Slides
        working-directory: slides/${{ matrix.slide.name }}
        run: npm run build
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v4.4.3
        with:
          name: slides-${{ matrix.slide.name }}
          path: slides/${{ matrix.slide.name }}/public
  deploy:
    needs: [build-slides]
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          sparse-checkout: |
            index.html
            talks.toml
          sparse-checkout-cone-mode: false
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: slides-running-kernel-based-virtual-machine
          path: public/running-kernel-based-virtual-machine
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: slides-governing-azure-resources-with-policy
          path: public/governing-azure-resources-with-policy
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: slides-tracking-nixpkgs-merged-pull-requests
          path: public/tracking-nixpkgs-merged-pull-requests
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: slides-demystifying-the-nix-store
          path: public/demystifying-the-nix-store
      - name: Prepare Public Directory
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: |-
          mkdir --parents public
          sed "s/YOUR_GOOGLE_MAPS_API_KEY/${GOOGLE_MAPS_API_KEY}/g" index.html > public/index.html
          cp talks.toml public/talks.toml
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: public/
      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
